### ISSUE TITLE
TODO Update DBDBuilder to the Newest Version

### ISSUE THREAD

**Issue by SaengerItsWar** [SaengerItsWar/dbdbuilder#1]
- [x] Add the New Killer and Survivor
- [x] Add the New Perks for the Killer and Survivor
- [x] Add the New Add-ons for the Killer
- [x] Look for other changes they made
- [x] Add the New Pictures
- [x] Deploy everything to the web server
